// Code generated by resert; DO NOT EDIT.

package testpkg

func (x *MyStruct) Reset() {
	x.ID = 0
	x.Name = ""
	x.Tags = x.Tags[:0]
	clear(x.Options)
	if x.Ptr != nil {
		*x.Ptr = 0
	}
	x.Embed = Embedded{}
}
