// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/FedorSidorow/shortener/internal/handler (interfaces: ShortenerServicer)

// Package handlers is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	models "github.com/FedorSidorow/shortener/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockShortenerServicer is a mock of ShortenerServicer interface.
type MockShortenerServicer struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerServicerMockRecorder
}

// MockShortenerServicerMockRecorder is the mock recorder for MockShortenerServicer.
type MockShortenerServicerMockRecorder struct {
	mock *MockShortenerServicer
}

// NewMockShortenerServicer creates a new mock instance.
func NewMockShortenerServicer(ctrl *gomock.Controller) *MockShortenerServicer {
	mock := &MockShortenerServicer{ctrl: ctrl}
	mock.recorder = &MockShortenerServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerServicer) EXPECT() *MockShortenerServicerMockRecorder {
	return m.recorder
}

// DeleteListUserURLs mocks base method.
func (m *MockShortenerServicer) DeleteListUserURLs(arg0 context.Context, arg1 uuid.UUID, arg2 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteListUserURLs", arg0, arg1, arg2)
}

// DeleteListUserURLs indicates an expected call of DeleteListUserURLs.
func (mr *MockShortenerServicerMockRecorder) DeleteListUserURLs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteListUserURLs", reflect.TypeOf((*MockShortenerServicer)(nil).DeleteListUserURLs), arg0, arg1, arg2)
}

// GenerateShortURL mocks base method.
func (m *MockShortenerServicer) GenerateShortURL(arg0 context.Context, arg1, arg2 string, arg3 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateShortURL", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateShortURL indicates an expected call of GenerateShortURL.
func (mr *MockShortenerServicerMockRecorder) GenerateShortURL(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateShortURL", reflect.TypeOf((*MockShortenerServicer)(nil).GenerateShortURL), arg0, arg1, arg2, arg3)
}

// GetListUserURLs mocks base method.
func (m *MockShortenerServicer) GetListUserURLs(arg0 context.Context, arg1 uuid.UUID, arg2 string) ([]*models.UserListJSONShortenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListUserURLs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.UserListJSONShortenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListUserURLs indicates an expected call of GetListUserURLs.
func (mr *MockShortenerServicerMockRecorder) GetListUserURLs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListUserURLs", reflect.TypeOf((*MockShortenerServicer)(nil).GetListUserURLs), arg0, arg1, arg2)
}

// GetURLByKey mocks base method.
func (m *MockShortenerServicer) GetURLByKey(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByKey", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByKey indicates an expected call of GetURLByKey.
func (mr *MockShortenerServicerMockRecorder) GetURLByKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByKey", reflect.TypeOf((*MockShortenerServicer)(nil).GetURLByKey), arg0)
}

// ListGenerateShortURL mocks base method.
func (m *MockShortenerServicer) ListGenerateShortURL(arg0 context.Context, arg1 []models.ListJSONShortenRequest, arg2 string) ([]models.ListJSONShortenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGenerateShortURL", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.ListJSONShortenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGenerateShortURL indicates an expected call of ListGenerateShortURL.
func (mr *MockShortenerServicerMockRecorder) ListGenerateShortURL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGenerateShortURL", reflect.TypeOf((*MockShortenerServicer)(nil).ListGenerateShortURL), arg0, arg1, arg2)
}

// PingStorage mocks base method.
func (m *MockShortenerServicer) PingStorage() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingStorage")
	ret0, _ := ret[0].(bool)
	return ret0
}

// PingStorage indicates an expected call of PingStorage.
func (mr *MockShortenerServicerMockRecorder) PingStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingStorage", reflect.TypeOf((*MockShortenerServicer)(nil).PingStorage))
}
